# Generated by Django 4.1.7 on 2023-03-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_ID', models.CharField(max_length=256, unique=True, verbose_name='监控指标ID')),
                ('metric_name', models.CharField(max_length=64, unique=True, verbose_name='指标名称')),
                ('metric_type', models.CharField(max_length=64, verbose_name='指标类型')),
                ('metric_desc', models.CharField(max_length=256, verbose_name='指标描述')),
                ('metric_unit', models.CharField(max_length=256, verbose_name='指标单位')),
                ('collect_type', models.SmallIntegerField(choices=[(0, 'Agent'), (1, '插件'), (2, '协议')], default=0, verbose_name='指标采集类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '监控指标表',
                'verbose_name_plural': '监控指标表',
                'db_table': 'metrics',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MonitorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('hardware_device_layer', '硬件设备层'), ('operating_system_layer', '操作系统层'), ('component_service_layer', '组件服务层'), ('application_performance_layer', '应用性能层')], default='hardware_device_layer', max_length=64, verbose_name='监控对象层级')),
                ('object_name', models.CharField(max_length=64, verbose_name='监控对象名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '监控对象表',
                'verbose_name_plural': '监控对象表',
                'db_table': 'monitorobject',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SysInfoManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sys_name', models.CharField(max_length=64, verbose_name='系统全称')),
                ('Sys_abbreviation', models.CharField(max_length=64, verbose_name='系统简称')),
                ('Sys_level', models.CharField(choices=[('first_level_layer', '一级系统'), ('second_level_layer', '二级系统'), ('third_level_layer', '三级系统')], default='third_level_layer', max_length=64, unique=True, verbose_name='系统等级')),
                ('Sys_dev_pricipal', models.CharField(max_length=32, verbose_name='系统开发负责人')),
                ('Sys_ops_pricipal', models.CharField(max_length=32, verbose_name='系统运维负责人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统信息管理',
                'verbose_name_plural': '系统信息管理',
                'db_table': 'sysinfomanage',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SysinfoMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '停用'), (1, '启用')], default=0, verbose_name='监控指标启停状态')),
                ('metrics_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.metrics')),
                ('sysinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.sysinfomanage')),
            ],
            options={
                'verbose_name': '系统与指标关联表',
                'db_table': 'sysinfometrics',
            },
        ),
        migrations.AddField(
            model_name='metrics',
            name='monitor_object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.monitorobject'),
        ),
    ]
