# Generated by Django 4.1.7 on 2023-03-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('hardware_device_layer', '硬件设备层'), ('operating_system_layer', '操作系统层'), ('component_service_layer', '组件服务层'), ('application_performance_layer', '应用性能层')], default='hardware_device_layer', max_length=64, verbose_name='监控对象层级')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='监控对象名称')),
                ('object_id', models.CharField(max_length=64, unique=True, verbose_name='监控对象对应监控指标id')),
                ('status', models.SmallIntegerField(choices=[(0, '停用'), (1, '启用')], default=0, verbose_name='监控对象启停状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '监控对象表',
                'verbose_name_plural': '监控对象表',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SysInfoManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sys_name', models.CharField(max_length=64, verbose_name='系统全称')),
                ('Sys_abbreviation', models.CharField(max_length=64, verbose_name='系统简称')),
                ('Sys_level', models.CharField(choices=[('first_level_layer', '一级系统'), ('second_level_layer', '二级系统'), ('third_level_layer', '三级系统')], default='third_level_layer', max_length=64, unique=True, verbose_name='系统等级')),
                ('Sys_dev_pricipal', models.CharField(max_length=32, verbose_name='系统开发负责人')),
                ('Sys_ops_pricipal', models.CharField(max_length=32, verbose_name='系统运维负责人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('object_id', models.ManyToManyField(to='MonitorCenter.monitorobject')),
            ],
            options={
                'verbose_name': '系统信息管理',
                'verbose_name_plural': '系统信息管理',
                'ordering': ['-create_time'],
            },
        ),
    ]
