# Generated by Django 4.1.7 on 2023-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('hardware_device_layer', '硬件设备层'), ('operating_system_layer', '操作系统层'), ('component_service_layer', '组件服务层'), ('application_performance_layer', '应用性能层')], default='hardware_device_layer', max_length=64, verbose_name='监控对象层级')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='监控对象名称')),
                ('status', models.SmallIntegerField(choices=[(0, '停用'), (1, '启用')], default=0, verbose_name='监控对象启停状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '监控对象表',
                'verbose_name_plural': '监控对象表',
                'ordering': ['-create_time'],
            },
        ),
    ]
