# Generated by Django 4.1.7 on 2023-03-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysinfomanage',
            name='metrics_sys',
            field=models.ManyToManyField(to='MonitorCenter.metrics'),
        ),
        migrations.DeleteModel(
            name='SysinfoMetrics',
        ),
    ]
