# Generated by Django 4.1.7 on 2023-03-20 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0002_sysinfomanage_metrics_sys_delete_sysinfometrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='Threshold',
            field=models.SmallIntegerField(default=0, verbose_name='阈值'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='trigger_rule',
            field=models.CharField(choices=[('greater', '>'), ('less', '<'), ('equal', '='), ('unequal', '≠'), ('greater_equal', '≥'), ('less_equal', '≤')], default='less', max_length=256, verbose_name='触发规则'),
        ),
        migrations.CreateModel(
            name='HostsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=64, verbose_name='IP地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.monitorobject', verbose_name='对象模块ID')),
                ('sys_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.sysinfomanage', verbose_name='系统ID')),
            ],
            options={
                'verbose_name': '系统信息管理',
                'verbose_name_plural': '系统信息管理',
                'db_table': 'hostinfo',
                'ordering': ['-create_time'],
            },
        ),
    ]
