# Generated by Django 4.1.7 on 2023-03-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0003_metrics_threshold_metrics_trigger_rule_hostsinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostsinfo',
            options={'ordering': ['-create_time'], 'verbose_name': '主机IP信息管理', 'verbose_name_plural': '主机IP信息管理'},
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Threshold',
            field=models.IntegerField(default=0, verbose_name='阈值'),
        ),
        migrations.AlterField(
            model_name='sysinfomanage',
            name='Sys_level',
            field=models.CharField(choices=[('first_level_layer', '一级系统'), ('second_level_layer', '二级系统'), ('third_level_layer', '三级系统')], default='third_level_layer', max_length=64, verbose_name='系统等级'),
        ),
    ]
