# Generated by Django 4.1.7 on 2023-03-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0004_alter_hostsinfo_options_alter_metrics_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysinfomanage',
            name='metrics_sys',
        ),
        migrations.AddField(
            model_name='metrics',
            name='metrics_sys',
            field=models.ManyToManyField(related_name='metrics_sys', to='MonitorCenter.sysinfomanage'),
        ),
    ]
